apiVersion: v1
kind: Service
metadata:
  name: censor-mongodb-nodeport
  namespace: censor
spec:
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: NodePort
