# mongodb-pv.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: censor-mongodb-pv
  namespace: censor
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/maestros/dev-maes/data/censor/deployment/kubernates/pv/censor-mongodb-pv
