version: "3"

services:
  redis:
    image: redis:buster
    container_name: redis
    ports:
      - "6379:6379"

  flask:
    container_name: flask
    restart: always
    build: ./src/backend/python/censor-management-prod
    ports:
      - "9000:9000"
    depends_on:
      - redis

  web:
    container_name: web
    build:
      context: ./src/frontend/dash-plotly
    ports:
      - "8085:8085"
    depends_on:
      - flask