apiVersion: v1
kind: Service
metadata:
  name: censor-redis-nodeport
  namespace: censor
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: NodePort
