# redis-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-censor-redis-deployment-master-0
  namespace: censor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-censor-redis-deployment-replicas-0
  namespace: censor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
