# storageClass.yml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: censor-influxdb-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: local
  path: /home/maestros/dev-maes/data/censor-management/deployment/kubernates/pv/censor-influxdb-pv

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: censor-redis-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: local
  path: /home/maestros/dev-maes/data/censor-management/deployment/kubernates/pv/censor-redis-pv

  