apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: censor-management-space
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP