# influxdb-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: censor-influxdb-deployment
  namespace: censor
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 160Mi
  volumeName: censor-influxdb-pv
